routes/web.php
<?php

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('login-gate/{token}', 'Auth\LoginController@loginGate');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
// Authentication Routes...
Route::middleware(['auth'])->group(function(){
    Route::get('/', 'HomeController@index')->name('index');
    Route::resource('activation', 'ActivationController');
    Route::apiResource('user', 'UserController');
    Route::apiResource('activation-question', 'ActivationQuestionController');

    //Aditional services
    Route::get('company-activations', 'ActivationController@apiGetData')->name('activations.company.get');
    Route::get('users-get', 'UserController@GetUsers')->name('users.get');
    Route::get('roles-get', 'UserController@GetRoles')->name('roles.get');
    Route::get('companies-get', 'CompanyController@GetCompanies')->name('companies.get');
    Route::get('question-type', 'QuestionTypeController@index')->name('question-type.index');
});

Route::get('test-dfm', function() {

    $activationSection = [
        'company_activation_id' => 1,
        'title' => 'Mi first activation',
        'page' => 1,
    ];
    \App\ActivationSection::create($activationSection);

    $questions = [
        [
            'activation_section_id' => 1,
            'question_type_id' => 1,
            'question' => 'This is my question',
            'options' => null,
            'order' => 1,
            'caption' => 'my caption',
            'required' => true,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 2,
            'question' => 'This is my question 2',
            'options' => json_encode(['val1'=>'opc1', 'val2'=>'opc2','val3'=>'opc3','val4'=>'opc4','val5'=>'opc5','val6'=>'opc6',]),
            'order' => 2,
            'caption' => 'my caption 2',
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 3,
            'question' => 'This is my question 3',
            'options' => json_encode(['val1'=>'opc1', 'val2'=>'opc2','val3'=>'opc3','val4'=>'opc4','val5'=>'opc5','val6'=>'opc6',]),
            'order' => 3,
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 4,
            'question' => 'This is my question 4',
            'options' => json_encode(['val1'=>'opc1', 'val2'=>'opc2','val3'=>'opc3','val4'=>'opc4','val5'=>'opc5','val6'=>'opc6',]),
            'order' => 4,
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 5,
            'question' => 'This is my question 5',
            'order' => 5,
            'restrictions' => json_encode(['min'=>10, 'max'=>20]),
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 6,
            'question' => 'This is my question 6',
            'order' => 6,
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 7,
            'question' => 'This is my question 7',
            'order' => 7,
            'restrictions' => json_encode(['min'=>'today', 'max'=>'+;20;d']),
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 8,
            'question' => 'This is my question 8',
            'order' => 8,
            'required' => false,
        ], [
            'activation_section_id' => 1,
            'question_type_id' => 9,
            'question' => 'This is my question 9',
            'order' => 9,
            'required' => false,
        ]
    ];

    foreach ($questions as $question) {   
        \App\ActivationQuestion::create($question);
    }

});

resources/views/modules/content.blade.php
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <toast></toast>
                    @yield('content')
                </div>
            </div>
        </div> <!-- container-fluid -->
        
    </div> <!-- content -->
    
    <footer class="footer">
        2019 © Atelier. <span class="d-none d-sm-inline-block"> - Daniel Flórez Murillo</span>
    </footer>
    
    
</div>

<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->

resources/views/modules/header.blade.php
<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <!-- Image logo -->
        <a href="" class="logo">
            <span>
                <img src="{{ asset('images/misc/logo-atelier.png') }}" alt="">
            </span>
        </a>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">

            <!-- Navbar-left -->
            <ul class="nav navbar-left">

            </ul>

            <!-- Right(Notification) -->
            <ul class="nav navbar-right list-inline">
                {{-- <li class="d-none d-sm-block list-inline-item">
                    <form role="search" class="app-search">
                        <input type="text" placeholder="Search..." class="form-control">
                        <a href=""><i class="fa fa-search"></i></a>
                    </form>
                </li> --}}
                <li class="list-inline-item">
                    <div class="dropdown">
                        <a href="#" class="right-menu-item dropdown-toggle" data-toggle="dropdown">
                            <i class="fas fa-bell"></i>
                            <span class="badge badge-pill badge-pink">4</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-right dropdown-lg user-list notify-list">
                            <li class="list-group notification-list m-b-0">
                                <div class="slimscroll">
                                    <!-- list item-->
                                    <a href="javascript:void(0);" class="list-group-item">
                                        <div class="media">
                                            <div class="media-left p-r-10">
                                                <em class="fa fa-diamond bg-primary"></em>
                                            </div>
                                            <div class="media-body">
                                                <h5 class="media-heading">A new order has been placed A new order has
                                                    been placed</h5>
                                                <p class="m-0">
                                                    There are new settings available
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </li>
                            <!-- end notification list -->
                        </ul>
                    </div>
                </li>

                <li class="dropdown user-box list-inline-item">
                    <a href="" class="dropdown-toggle waves-effect user-link" data-toggle="dropdown" aria-expanded="true">
                        <img
                            src="{{ Auth::user()->avatar() }}"
                            alt="user-img" class="rounded-circle user-img">
                    </a>

                    <ul
                        class="dropdown-menu dropdown-menu-right arrow-dropdown-menu arrow-menu-right user-list notify-list">
                        <li><a href="javascript:void(0)" class="dropdown-item">{{ Auth::user()->name }}</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a href="javascript:void(0)" class="dropdown-item">Profile</a></li>
                        <li><a href="javascript:void(0)" class="dropdown-item">Settings</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a href="{{ route('logout') }}" class="dropdown-item">Logout</a></li>
                    </ul>
                </li>

                <li class="list-inline-item mobile-menu d-xl-none d-lg-none">
                    <a href="#" class="waves-effect user-link" id="mobile-menu-button">
                        <i class="fas fa-bars fa-2x"></i>
                    </a>
                </li>

            </ul> <!-- end navbar-right -->

        </div><!-- end container-fluid -->
    </div><!-- end navbar -->
</div>
<!-- Top Bar End -->

resources/views/modules/left_sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="left side-menu">
    <div class="slimscroll-menu" id="remove-scroll">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">

                <li>
                    <a href="{{ route('index') }}">
                        <i class="fas fa-chart-bar"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                @if(Auth::user()->accessEditor())
                <li class="menu-title">Editores</li>
                <li class="{{ (Request::is('activation'))?'mm-active':'' }}">
                    <a class="{{ (Request::is('activation'))?'mm-active':'' }}" href="{{ route('activation.index') }}">
                        <i class="fas fa-edit"></i>
                        <span>Activaciones</span>
                    </a>
                </li>
                @endif

                @if(Auth::user()->accessCompany())
                <li class="menu-title">Administrador</li>
                <li class="{{ (Request::is('user'))?'mm-active':'' }}">
                    <a href="{{ route('user.index') }}" class="{{ (Request::is('user'))?'mm-active':'' }}">
                        <i class="fas fa-users"></i>
                        <span>Usuarios</span>
                    </a>
                </li>
                {{-- @if(Auth::user()->accessEditor())
                <li class="{{ (Request::is('company'))?'mm-active':'' }}">
                    <a href="{{ route('user.index') }}" class="{{ (Request::is('company'))?'mm-active':'' }}">
                        <i class="fas fa-building"></i>
                        <span>Empresas</span>
                    </a>
                </li>
                @endif --}}
                @endif

                {{-- @if(Auth::user()->role(['company', 'user_company']))
                <li class="menu-title">Usuario</li>
                <li>
                    <a href="{{ route('index') }}">
                <i class="fas fa-chart-bar"></i>
                <span>Crear Activación</span>
                </a>
                </li>
                @endif --}}

                @if(Auth::user()->accessAdmin())
                <li class="menu-title">Root</li>
                <li>
                    <a href="{{ route('index') }}">
                        <i class="fas fa-users"></i>
                        <span>Usuarios Globales</span>
                    </a>
                </li>
                @endif

            </ul>

        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->